[package]
name = "sbe-watch"
version = "0.4.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
notify.workspace = true
sbe-events.workspace = true
sbe-indexer.workspace = true
sbe-scanner.workspace = true
serde.workspace = true
