[package]
name = "sbe-context"
version = "0.3.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rustc-hash.workspace = true
sbe-common.workspace = true
sbe-graph.workspace = true
sbe-symbols.workspace = true
serde.workspace = true
smallvec.workspace = true
